---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: irsa-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::205930612588:role/irsa-example
---
apiVersion: v1
kind: Pod
metadata:
  name: irsa-test
  namespace: default
spec:
  serviceAccountName: irsa-sa
  restartPolicy: Always
  containers:
    - name: aws-cli
      image: public.ecr.aws/aws-cli/aws-cli:latest
      command: ["/bin/bash", "-c"]
      args:
        - |
          while true; do
            echo "Verificando a identidade IAM..."
            aws sts get-caller-identity
            echo "Listando buckets do S3..."
            aws s3 ls
            echo "===================================="
            echo "Aguardando 3 minutos..."
            sleep 180
            echo "===================================="
          done
      # tty: true
---
