apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-ingress
  namespace: kube-monitoring
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
    # nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - host: grafana.compwave.com.br
    http:
      paths:
      - backend:
          service:
            name: kube-prometheus-stack-grafana
            port:
              number: 3000
        path: /
        pathType: ImplementationSpecific
  - host: prometheus.compwave.com.br
    http:
      paths:
      - backend:
          service:
            name: prom-stack-infra-prometheus
            port:
              number: 9090
        path: /
        pathType: ImplementationSpecific
    http:
      paths:
      - backend:
          service:
            name: prom-stack-infra-alertmanager
            port:
              number: 9093
        path: /
        pathType: ImplementationSpecific
