apiVersion: v1
kind: Namespace
metadata:
  name: ingress
---
apiVersion: v1
kind: Namespace
metadata:
  name: devops
---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: infra
